name: smart_attendance_system
description: "A mobile-first biometric attendance management platform for universities. Administrators register students and lecturers, manage faculties and departments, and oversee fingerprint enrollment. Lecturers create classes, select pre-defined student groups, and capture attendance via fingerprint scanning. The system provides real-time analytics, secure record-keeping, and eliminates proxy attendance through biometric verification."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.1.4
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  flutter_bloc: ^9.1.1
  go_router: ^16.3.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.5.0
  dio: ^5.9.0
  get_it: ^8.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700